### PR TITLE
Maintenance Page: page updated with layouts

### PR DESCRIPTION
**Pull request by JuanJosePG**

### CODE REVIEW

**Comment by Andresws12** [comment]
@JuanJosePG Resolve the conlficts please

**Comment by JuanJosePG** [comment]
Confilct resolved. I think the reason was because the ButtonTranslation.vue was in another folder. I didn't do a git pull before starting the task.

If @PVillasana @gonzalo-plaza or someone can check it to merge.

**Comment by gonzalo-plaza** [comment]
@JuanJosePG  @Andresws12 For me this is ready to merge now

**Comment by Andresws12** [comment]
For me it's okay I will merge it cause @PVillasana  never answer jajajaka

**Pull request merged**
